# Generated by Django 4.0.6 on 2022-07-27 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmarks', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficInfo',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('traveled_d', models.FloatField()),
                ('avg_speed', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField()),
                ('lon_acc', models.FloatField()),
                ('lat_acc', models.FloatField()),
                ('time', models.FloatField()),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='endpoints.location')),
            ],
        ),
    ]
